### ISSUE TITLE
Tracking stops in middle of night?

### ISSUE THREAD

**Issue by MatthiasKauer** [npenkov/pebslee-pebble#1] opened 2014-12-09 15:21 UTC
Hi,
let me begin by saying that I really like the way you're approaching the sleep tracking by making the watch by itself as useful as possible.
I have some issue with getting to the data reliably however or maybe I just don't understand.
I set an alarm yesterday night around 23:00 to 6:40 - 6:59 this morning. It asked whether I want to take away sensors from Morpheuz which I confirmed.
I went to sleep and the alarm somehow didn't trigger. Now (around 10:00) here, I find in the manual that long pressing tracking brings up the statistics screen and it shows that I only slept till 2:30 or so which is somewhat odd.

Should I supply some data so you can track this better?

Best regards,
Matthias

PS: Is there / could you add a small version string somewhere so I can easily tell you what version I'm on when I'm submitting such a report.

**Comment by MatthiasKauer** [comment] 2014-12-09 15:23
Also: The watch face is exited very easily (too easy for my taste) when pressing 'back'. This left me stranded at another occasion. Today however, the watch face was still on when I woke up.

Does the watch face even need to be up for tracking to work?

**Comment by npenkov** [comment] 2014-12-09 18:28
Hi Matthias,
Thanks for the note - having a version somewhere for support reasons is quite a good idea. I will include it probably on startup, or maybe with Info screen.
For the back button - you might be right - I will consider making exit from application with long pressing the button. So far I had no problems with it.
Here are some explanations - so PebSlee is not a watchface, rather than application - when you press back from the main screen - you actually close the application. There is a background process running only when the tracking is active - the goal is to suppress the background trackers like Jawbone UP to reset the application. When you start the tracking, the OS (pebble) asks you if the background process should be switched to PebSlee - means stoping the other background processes.
PebSlee cannot operate so far in background - I don't even think I will implement this, as when having a wakeup app - it should be in foreground whole night (nobody is expected during sleep to do something else with the watch :-) ). BTW - one way to check if you are running the latest version is to check if you have in the status bar (top) one small walking figure. If you have this, and when activating the monitoring (in PebSlee) it does not ask you for switching the background process - then for sure you have old version, and some other background process that can stop PebSlee at midnight.
As for the the weird behaviour - I cannot find any other reason than having the old version, where the background process is not running - and some other application wakes up and flushes PebSlee monitoring activity.
Hope that this helps a bit.
BTW - If you have further questions or suggestions, I would prefer if you post then on PebSlee.com, so that they are visible for others too. I would prefer to keep in github only reproducible bugs and pull requests, that can be further linked to release versions.

Thanks and Regards,
Nick

**Comment by MatthiasKauer** [comment] 2014-12-10 00:19
Hi Nick,
thank you for the clarification.

I have updated to the last version today (uninstalled and re-installed via Pebble Android app) and will try this again.

Where on pebslee.com would you like discussions like this to happen?
I had the impression that this issue tracker is a good spot actually.

**Comment by npenkov** [comment] 2014-12-10 08:19
Hi Matthias,
For the issues, at least my vision is, that github will be for some bugs that are pinpointed in the code. And for the ones that are more general, also for suggested features, we have created pebslee domain where there are more possibilities for discussions, voting for features etc.
If you feel like structuring your suggestions on pebslee, so that others can also see them, you can post a comment anywhere you feel like. Don't feel obliged to - I have taken notes for the ideas.
I hope that with the new version, you don't experience the issues you have, if not - will look forward to your feedback.

Cheers,
Nick

**Comment by npenkov** [comment] 2015-07-11 13:32
Back button functionality fixed in v.1.5. The stopping of tracking due to notification - will be fixed with next version, where the tracking is done in background worker. Commit [0425389]

**Closed as completed by npenkov** 2015-07-11 13:32 UTC
